routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => ['auth']], function () {
	Route::get('clients/datatable','ClientController@datatable')->name('clients.datatable');
	Route::get('clients/report/pdf','ClientController@reportPdf')->name('clients.report.pdf');
	Route::get('clients/report','ClientController@viewReport')->name('clients.report');
	Route::resource('clients', 'ClientController');
	Route::get('/', 'HomeController@index')->name('home');
});
Auth::routes();

resources/views/client.blade.php
@extends('welcome')
@section('content')
    <div class="card">
      <div class="card-header">
        Listado de Clientes
      </div>
      <div class="card-body ">
        <div class="row p-3">
            <div class="col-4">
                <label>Concesionario:</label>
                <select   id="dealer_id" class="form-control" required="">  
                    <option>Seleccione</option>
                    @foreach($dealers as $dealer) 
                    <option  value="{{ $dealer->id }}">{{ $dealer->description }}</option>
                    @endforeach
                </select>       
            </div>
            <div class="col-4">
                <label>Localidad:</label>
                <select   id="locality_id" class="form-control" required="">  
                    <option>Seleccione</option>
                    @foreach($locations as $location) 
                        <option value="{{ $location->id }}">{{ $location->description }}</option>
                    @endforeach
                </select>       
            </div>
            <div class="col-3">
                <button type="button" class="btn btn-block btn-primary" data-toggle="modal" data-target="#createModal">
                  Registrar Cliente
                </button>
            </div>
        </div>
        <div class="row">
            <div class="col-12 p-3">
                <button class="btn btn-danger"><i class="fa fa-file-pdf-o" aria-hidden="true"></i></button>
                
            </div>
        </div>
        <div class="row mt-5">
            <div class="col-12">
                <table id="clientsGrilla" class="mt-5 table table-borderless table-striped table-earning w-100" cellspacing="0">
                    <thead>
                        <tr>
                            <th data-priority="0">Nombre</th>
                            <th>Cédula</th>
                            <th>Teléfono</th>
                            <th>Concesionario</th>
                            <th data-priority="1">Acción</th>
                        </tr>
                    </thead>
                    <tfoot class="filter">
                        <tr>
                            <td>Nombre</td>
                            <td>Cédula</td>
                            <td>Teléfono</td>
                            <td>Concesionario</td>
                            <td class="no-filter"></td>
                        </tr>
                    </tfoot>
                    <tbody>

                    </tbody>
                </table>
            </div>
        </div>
      </div>
    </div>
@endsection

<div class="modal fade" id="createModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Nuevo Cliente</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>

      </div>
      <form action="{{route('clients.store')}}" method="post" id="createForm" data-parsley-validate='' novalidate='' data-parsley-excluded='[disabled]'data-parsley-focus='first'>
          <div class="modal-body">
              <div class="form-group">
                <label for="dni">Cédula</label>
                <input type="text" class="form-control" name="dni" id="dni" placeholder="Nombres" required>
              </div>
              <div class="form-group">
                <label for="first_name">Nombres</label>
                <input type="text" class="form-control" name="first_name" id="first_name" placeholder="Cédula" required>
              </div>
              <div class="form-group">
                <label for="last_name">Apellidos</label>
                <input type="text" class="form-control" name="last_name" id="last_name" placeholder="Apellidos" required>
              </div>                  
              <div class="form-group">
                <label for="email">Correo</label>
                <input type="email" class="form-control" id="email" name="email" aria-describedby="emailHelp" placeholder="Correo" required>
              </div>
              <div class="form-group">
                <label for="telephone_number">Teléfono</label>
                <input type="text" class="form-control phone" name="telephone_number" id="telephone_number" placeholder="(0212)-555.55.55" required>
              </div>  
                <div class="form-group">
                    <label>Localidad:</label>
                    <select  name="locality_id" class="form-control" required="">  
                        <option>Seleccione</option>
                        @foreach($locations as $location) 
                        <option value="{{ $location->id }}">{{ $location->description }}</option>
                        @endforeach
                    </select>
                </div>
                <div class="form-group">
                    <label>Concesionario:</label>
                    <select  name="dealer_id" class="form-control" required="">  
                        <option>Seleccione</option>
                        @foreach($dealers as $dealer) 
                        <option  value="{{ $dealer->id }}">{{ $dealer->description }}</option>
                        @endforeach
                    </select>
                </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
            <button type="subtmi" class="btn btn-success">Guardar</button>
          </div>
      </form>
    </div>
  </div>
</div>

@section('javascript')
    <script>
        (()=>{
            class App{
                constructor(){
                    this.eventCreate()
                    this.routeDatatable="{{route('clients.datatable')}}";
                    this.routeModal="{{route('clients.edit',":slug")}}";
                    this.routeModalView="{{route('clients.show',":slug")}}";
                    this.routeModalDelete="{{route('clients.destroy',":slug")}}";
                    this.position="{{session('cargo_id')}}";
                    this.divDatatable='#clientsGrilla';
                    this.ColumnsDatatable=[
                        {data: 'full_name'},
                        {data: 'dni'},
                        {data: 'telephone_number'},
                        {data: 'dealer'},
                        {data: 'actions'},
                    ];
                    this.dataDatatable;
                    this.table;
                    this.arrayCondition;
                    this.showDataTable()
                }
                eventCreate(){
                    let self=this;
                    $('#createModal').on("submit","#createForm",function(event){
                        event.preventDefault()
                        let form = $(this);
                        let data=form.serialize();
                        saveForm(form,data)
                        .then(
                            (data)=>{
                                $('#createModal').modal('hide');
                                alert()
                                notifyMessage(data.menj,'Operación Exitosa.','success');
                                self.table.oTable.ajax.reload();
                            },
                            (error)=>{
                                if(error.error==1){
                                    notifyMessage('Debe seleccionar una respuesta correcta para el tipo de pregunta seleccionada.','Error de datos','info');
                                }else if(error.error==2){
                                    notifyMessage('Debe existir más de una respuesta.','Error de datos','info');
                                }
                            }
                        )
                    })
                }
                maskPhone(div){
                    div.mask('(0000) 000-00.00')
                }
                showDataTable(){
                    //***Crear DataTable***//
                    this.table=new DataTableApp(this.routeDatatable,this.divDatatable,this.ColumnsDatatable,this.dataDatatable,this.arrayCondition);
                    //*** Filtros individuales para cada columna ***//
                    this.table.filters();

                     //***Evento de editar cliente ***//
                    this.table.eventDetail('#edit',(data)=>{
                        let self=this;
                        // se obtiene el id del registro para enviarlo al formulario
                        let idClient=data.id;
                        let url = this.routeModal.replace(':slug', idClient);

                        loadModal(url,'#modalEditClient',data,function(){
                            $('#modalEditClient').on("submit","#procesarForm",function(event){
                                event.preventDefault();
                                let form = $(this);
                                let data=form.serialize()+"&id="+idClient;
                                saveForm(form,data)
                                .then((data)=>{
                                    $('#modalEditClient').modal('hide');
                                    notifyMessage(data.menj,'Registro exitoso','success');
                                    self.table.oTable.ajax.reload();
                                })

                            });    
                        });
                   });
                    this.table.filter(()=>{
                        $('#dealer_id').change((event)=> {
                            this.table.myData.dealer_id = $('#dealer_id').val();
                            this.table.oTable.ajax.url(this.routeDatatable).load();
                        });
                    })
                    this.table.filter(()=>{
                        $('#locality_id').change((event)=> {
                            this.table.myData.locality_id = $('#locality_id').val();
                            this.table.oTable.ajax.url(this.routeDatatable).load();
                        });
                    })
                    //*
                    //***Evento de agregar cliente ***//
                    this.table.eventDetail('#view',(data)=>{
                        let self=this;
                        // se obtiene el id del registro para enviarlo al formulario
                        let idClient=data.id;
                        let url = this.routeModalView.replace(':slug', idClient);
                        // se levanta la modal y se le envia la data
                        loadModal(url,'#modalViewClient',data);
                   });

                    //***Evento de eliminar participante ***//
                    this.table.eventDetail('#remove',(data,obj)=>{
                        let self=this;
                        // se obtiene el id del registro para enviarlo al formulario
                        let idClient=data.id;
                        bootbox.confirm({
                            title: "Confirmar Acción?",
                            message: `¿Está seguro que desea eliminar al cliente ${data.full_name}`,
                            buttons: {
                                cancel: {
                                    label: '<i class="fa fa-times"></i> Cancel'
                                },
                                confirm: {
                                    label: '<i class="fa fa-check"></i> Confirm'
                                }
                            },
                            callback: function (result) {
                                if(result){
                                    let url = self.routeModalDelete.replace(':slug', idClient);
                                    $.ajax({
                                        type: 'DELETE',
                                        url: url,
                                        dataType: 'json',//
                                        headers:{'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')},
                                        data: data,
                                    })
                                    .done(function(data) {
                                        if(data.tipo=="aprobado"){
                                            notifyMessage(data.menj,'','success');
                                            self.table.oTable.ajax.reload(); //recargar data de la tabla
                                        }else{
                                            notifyMessage(data.menj,'Error al realizar la modificación','danger');
                                        }
                                    })
                                    .fail(function(data) {
                                        notifyMessage('Ocurrió un error al procesar su formulario, comuníquese con el administrador del sistema','Error al realizar el registro','danger');
                                    });
                                }
                            }
                        });
                    });
                }
            }
            let app=new App();
            app.maskPhone($('.phone'));
        })();
    </script>
@stop

resources/views/edit.blade.php
<div class="modal fade" id="modalEditClient" tabindex="-1" role="dialog" aria-labelledby="largeModalLabel" aria-hidden="true">
	<div class="modal-dialog modal-md" role="document">
		<form action="{{route('clients.update',$request->id)}}" method="PUT" id="procesarForm" data-parsley-validate='' novalidate='' data-parsley-excluded='[disabled]'data-parsley-focus='first'>
		<div class="modal-content">
			<div class="modal-header">
				<h4 class="modal-title" id="largeModalLabel">Editar Clientes</h4>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-body">
				@include('form')				
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
				<button type="submit" class="btn btn-primary">Guardar</button>
			</div>
		</div>
		</form>
	</div>
</div>

resources/views/form.blade.php
<div class="row justify-content-center">
	<div class="col-md-12 col-md-auto">
        <div class="form-group">
			<label>Cédula:</label>
			<input type="text" class="form-control" value="{{ $request->dni }}" name="dni" readonly="" >
		</div>
    </div>
	<div class="col-md-12 col-md-auto">
        <div class="form-group">
			<label>Nombres:</label>
			<input type="text" class="form-control" value="{{ $request->first_name }}" name="first_name" @if(isset($exist)) readonly="" @endif>
		</div>
    </div>
    <div class="col-md-12 col-md-auto">
        <div class="form-group">
			<label>Apellidos:</label>
			<input type="text" class="form-control" value="{{ $request->last_name }}" name="last_name" @if(isset($exist)) readonly="" @endif>
		</div>
    </div>
    <div class="col-md-12 col-md-auto">
    <div class="form-group">
	    <label for="email">Correo</label>
	    <input type="email" class="form-control" id="email" name="email" value="{{ $request->email }}" aria-describedby="emailHelp" @if(isset($exist)) readonly="" @endif placeholder="Correo" required>
	  </div>
	</div>
    <div class="col-md-12 col-md-auto">
        <div class="form-group">
			<label>Teléfono:</label>
			<input type="text" class="form-control" value="{{ $request->telephone_number }}" name="telephone_number" @if(isset($exist)) readonly="" @endif>
		</div>
    </div>
	<div class="col-md-12 col-md-auto">
	    <div class="form-group">
			<label>Localidad:</label>
			<select  name="locality_id" class="form-control" required="" @if(isset($exist)) readonly="" @endif>  
				<option>Seleccione</option>
				@foreach($locations as $location) 
				<option @if($location->id == $request->locality_id) selected="" @endif value="{{ $location->id }}">{{ $location->description }}</option>
				@endforeach
			</select>
		</div>
	</div>
	<div class="col-md-12 col-md-auto">
	    <div class="form-group">
			<label>Concesionario:</label>
			<select  name="dealer_id" class="form-control" required="" @if(isset($exist)) readonly="" @endif>  
				<option>Seleccione</option>
				@foreach($dealers as $dealer) 
				<option @if($dealer->id == $request->dealer_id) selected="" @endif value="{{ $dealer->id }}">{{ $dealer->description }}</option>
				@endforeach
			</select>
		</div>
	</div>
</div>

resources/views/home.blade.php
<!doctype html>
<html lang="{{ app()->getLocale() }}">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">
        <title>Automotriz</title>

        <!-- Fonts -->
        <link href="{!! asset('css/font-awesome-4.7/css/font-awesome.min.css') !!}" media="all" rel="stylesheet" type="text/css" />
        <link href="{!! asset('css/bootstrap.min.css') !!}" media="all" rel="stylesheet" type="text/css" />
        <link href="{!! asset('css/datatable/datatable.min.css') !!}" media="all" rel="stylesheet" type="text/css" />
        <link href="{!! asset('css/estilos.css') !!}" media="all" rel="stylesheet" type="text/css" />
    </head>
    <body>
        <div id="modal-load">
            @yield('modal')
        </div>
        <div class="container-fluid">
            <div class="row">
                <div class="barra-lateral col-12 col-sm-auto">
                    @include('menu')
                </div>

                <main class="main col">
                    <div class="row justify-content-center">
                        <div class="col-10">
                            @yield('content')
                        </div>
                    </div>
                </main>
            </div>
        </div>
        <script type="text/javascript" src="{!! asset('js/jquery-3.2.1.min.js') !!}"></script>
        <script type="text/javascript" src="{!! asset('js/bootstrap-4.1/popper.min.js') !!}"></script>
        <script type="text/javascript" src="{!! asset('js/bootstrap-4.1/bootstrap.min.js') !!}"></script>
        <script type="text/javascript" src="{!! asset('js/parsley.min.js') !!}"></script>
        <script type="text/javascript" src="{!! asset('js/bootstrap-notify.js') !!}"></script>
        <script type="text/javascript" src="{!! asset('js/datatable/datatable.min.js') !!}"></script>
        <script type="text/javascript" src="{!! asset('js/mask.js') !!}"></script>
        <script type="text/javascript" src="{!! asset('js/bootbox.min.js') !!}"></script>
        <script type="text/javascript" src="{!! asset('js/main.js') !!}"></script>
        <script type="text/javascript" src="{!! asset('js/class/Datatable.js') !!}"></script>
        @yield('javascript')
    </body>
</html>

resources/views/menu.blade.php
<div class="logo">
    <h2>AutoMotriz</h2>
</div>
<nav class="menu d-flex d-sm-block justify-content-center flex-wrap">
    <a href="{{route('clients.index')}}"><span>Clientes</span></a>
    <a href="{{route('clients.report')}}"><span>Reporte</span></a>
    <a href="{{ route('logout') }}"
       onclick="event.preventDefault();
                     document.getElementById('logout-form').submit();">
        </i><span>Cerrar Sesión</span>
    </a>

    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
        @csrf
    </form>
</nav>

resources/views/report.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
</head>
<body>
    
</body>
</html>

resources/views/view.blade.php
<div class="modal fade" id="modalViewClient" tabindex="-1" role="dialog" aria-labelledby="largeModalLabel" aria-hidden="true">
	<div class="modal-dialog modal-md" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h4 class="modal-title" id="largeModalLabel">Detalle del cliente</h4>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-body">
				@include('form')
				
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
			</div>
		</div>
	</div>
</div>